name: Just Checkout
on:
  workflow_dispatch:
  schedule:
    # Run every 15 minutes
    - cron: '0/15 * * * *'
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2