name: Secret Scanner
on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
        with:
          baseline_file: ../.secrets.baseline
          python_version: "3.10.4" 