---
# Simple profile showing off the dependabot_configured rule
version: v1
type: profile
name: dependabot-github-actions-github-profile
display_name: Dependabot for GitHub Actions
context:
  provider: github
alert: "off"
remediate: "off"
repository:
  - type: pre_commit_github_action
    def:
      package_ecosystem: github-actions
      schedule_interval: daily
